[[Attr]]
arch = "aarch64"
git-tree-sha1 = "7551a9e37494d5d043b985ab7dace5fb93721a55"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "6530d1661ee8f3cabadd8e7db60844b1c666e6cd319fcaaa175acfdc83eb0cea"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.aarch64-linux-gnu.tar.gz"
[[Attr]]
arch = "aarch64"
git-tree-sha1 = "1dd090ee949ec4c685c8d59624dd404f3baca11e"
libc = "musl"
os = "linux"

    [[Attr.download]]
    sha256 = "0ce7618c67fdfb6e5d2ba0e4d55120bd77639f27368abc090abf776b15ff2d5d"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.aarch64-linux-musl.tar.gz"
[[Attr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8abb187de7c9c1195a078e9909324ee68ce1e470"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "94975c1e21f51f61d1d9325e33ba9e0e45b32a81d1e3d49c2bddf1fa79fc809d"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.armv6l-linux-gnueabihf.tar.gz"
[[Attr]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e9cc0f89b83b9defd1952fa7c733a6e029194574"
libc = "musl"
os = "linux"

    [[Attr.download]]
    sha256 = "522b62fbebec3f894ab9593551d9123ef89e611b3a4860faf31ee1ae52b3df7e"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.armv6l-linux-musleabihf.tar.gz"
[[Attr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fff5c33053227a44e67271a9b7dd0e1ef4cf22c1"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "54b421aed457bf1c7e70585066eb666078eaa68b493928e5c8ed978fe9e04d29"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.armv7l-linux-gnueabihf.tar.gz"
[[Attr]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "95c121287cb2ae5cae8f3e224a72a5d67116cd46"
libc = "musl"
os = "linux"

    [[Attr.download]]
    sha256 = "2a8bb03d7594c1f416c10589793d8774b9a5a31c4803d4fef0f4c56abe79d587"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.armv7l-linux-musleabihf.tar.gz"
[[Attr]]
arch = "i686"
git-tree-sha1 = "1157987903539d545a64cb6867a0d60c3e38b114"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "18bfed6d4909a00718c1ae2cff6375e44096df409513614919832729b67d62e0"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.i686-linux-gnu.tar.gz"
[[Attr]]
arch = "i686"
git-tree-sha1 = "da0df0392ea39cee19876008fb4602caddee7130"
libc = "musl"
os = "linux"

    [[Attr.download]]
    sha256 = "803da3aac127d318e19dbe671e6f397a7340de189fbca3c24d5e957843e2400d"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.i686-linux-musl.tar.gz"
[[Attr]]
arch = "powerpc64le"
git-tree-sha1 = "8792636753a55c33783c759944ab81ff56882cc6"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "cb3781e54b6f92156006e1974676c22abc774c923960a2dc808deb0e7d41914a"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.powerpc64le-linux-gnu.tar.gz"
[[Attr]]
arch = "x86_64"
git-tree-sha1 = "3c14801e77de4dc094435912f0273ff556ba8881"
libc = "glibc"
os = "linux"

    [[Attr.download]]
    sha256 = "3b70d42c900002dd6ad10076731cc608eb13e285094df69ffb524f967107e0e0"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.x86_64-linux-gnu.tar.gz"
[[Attr]]
arch = "x86_64"
git-tree-sha1 = "1a6774378dec0de805016740458a8e6d968a6325"
libc = "musl"
os = "linux"

    [[Attr.download]]
    sha256 = "b3c46a778e11c9d3730f4d5d9f0b7c37fa5357a888a2efd37978f81593909aca"
    url = "https://github.com/JuliaBinaryWrappers/Attr_jll.jl/releases/download/Attr-v2.5.2+0/Attr.v2.5.2.x86_64-linux-musl.tar.gz"
